language: node_js
dist: trusty
notifications:
  email: false
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
after_success:
  - npm run report-coverage
  - npm run semantic-release
before_deploy:
  - npm run build-storybook
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
env:
  global:
  - secure: FNvLzmIyC69nE8URXRtzfZyWMu798b4wXhkNn2q4PDyWwYgXjA3jD6uOjlUDF2Cf2tRhbxwFaed0IstlzPX3UhoJO0p9Z1GNh1COAQGrMoMXOPPnvuhvCzOeYsPIC6r/8Lt6w/m7YwQ3qYcEfy9/bzf8LKrLNTGpB5/HnmQCfsvRbQC97UL7JoX8BbPuFqyqtGNLDMFgVz2d9Z/OscJ6uUy/caK8Rj2NAh7GfNU1NV2LmZ4Z6Sy9RCqb+aCwaFQi/BkqLPrFOsXLTY18xYio3c33FjpgZvc+XGaaLMWj2Sd8jFEspcLkXBAKjrufzPNc+9V9ogGEuxEccgI2tQiM1TUs0+ng21zqlMk+e9Zo1d9aE+wKXMkIbevf35G/428vnjZJW9gJPtBoSuZdJziTZTTdJASn4wiZtxEuAYYHKKPhXlBob1GhvrQp3EJItpp5kI/l0EQEan5tWoh0y19z19RCCatYLMoZ6hPRNG5arWmOhmeNAJZ6AtsNJypcPP6KWvXfI7rfQGv7gUBWUgkLR0eC3FjCxxUgkHz1dumc5xZlVcgyjpbgDceNIoseznqdtnuGwUYIK4b5X8htoK9uG/EVbUhhCdAraAJFcZnuMWzqCoInP62z6l3GBTByX5bci4+Sje08v7XKru6nftFTBwXMJt4ioCl/jfNYIW0G9jM=
  - secure: k/Sd6YpTUriT/d2+A/2BeSV11KtWwkokCtUR+oEOKybsUye6eYd0yLu6Dgg6rDXNq+QmTwKNMGRGGNNpta3dgij75Kb6vQtS3NquZem9fr8ECECiRYgqeqJnvjvyoF40K3LcYdnzsGKk/m3nqb8R1xGfkeazwPgkp3mx4HC6wfsbpZ0ylEZd4grl/1n1NOXWcxVhhPK/tYG4ThDfGHhBKnCpaVBZ2ZHw46D/1yf2/zD0zNCvsWVg8LVa+uhHxvngkFqd+g9CyLQXQHeo6qHO8++zfN3xAqvFD4up75R32u/ypOFxqA67X6ce59APzgA5X8UQBfR0SzkBWnsCDCqUvFdB+WrHV3goWn0qcJ0vmhfGpal8EQncP9/sw1klcLA3O+gWWCBmEgUwmzZYwNcCuhtvwRd/1DKvcKfm9jHYq95fpJjYQUt6jJ9lpAuK0BArJSzpBqvSZGtH5SThnHmL3stJSO+dbq/PeI24EisHEnkC7XzP3a0hrM1te6rrNqNeCzb61Z1QePApflwc+8ocPsnj4pE6qpDLa6W2pd92mAoX8q+kHmIDl46H534fVvgoSSIkGKZYpANYbLeenJxchVfYk6CZfkBzbjzJMzgq/2zVbZ9NslIv29YvcliGNedNzpMhAj6G56QznQniWeERqQ6s6i1h6VM4gPpsJyTepvQ=
